name: Deploy

concurrency: 
  group: deploy

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: assets
    - name: Deploy to Static CDN
      uses: AyaInfra/StaticCDNDeploy@main
      with:
        deploy-credentials: ${{ secrets.STATIC_CDN_CREDENTIALS }}
        local-path: assets
        remote-path: libreoj-assets
